[workspace]
members = [
  "iterator-invalidation-rust",
  "uninitialized-rust",
  "variants-rust",
  "initialize-choice-rust",
  "printing-rust",
  "requirements-rust",
  "functional-iterators-rust",
  "error-messages-rust",
  "fearless-concurrency-rust",
]
